// AUTO-GENERATED by JavaPoet
package works.hop.javro.jdbc.dto;

import java.lang.String;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import works.hop.javro.jdbc.annotation.Column;
import works.hop.javro.jdbc.annotation.JoinColumn;
import works.hop.javro.jdbc.entity.Club;
import works.hop.javro.jdbc.entity.Member;

public class MyMembership {
  @Column("date_created")
  public LocalDate dateCreated;

  @Column("last_updated")
  public LocalDateTime lastUpdated;

  @JoinColumn("member_id")
  public Member member;

  @JoinColumn(
      value = "club_id",
      fkTable = "tbl_membership"
  )
  public List<Club> club;

  @Column("member_alias")
  public String alias;

  @Column("member_status")
  public String status;

  public MyMembership() {
  }

  public void setDateCreated(LocalDate dateCreated) {
    this.dateCreated = dateCreated;
  }

  public LocalDate setDateCreated() {
    return this.dateCreated;
  }

  public void setLastUpdated(LocalDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  public LocalDateTime setLastUpdated() {
    return this.lastUpdated;
  }

  public void setMember(Member member) {
    this.member = member;
  }

  public Member setMember() {
    return this.member;
  }

  public void setClub(List<Club> club) {
    this.club = club;
  }

  public List<Club> setClub() {
    return this.club;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public String setAlias() {
    return this.alias;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String setStatus() {
    return this.status;
  }
}
