package works.hop.field.model.generator;

import com.squareup.javapoet.*;
import works.hop.field.model.Node;

import javax.lang.model.element.Modifier;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

public class Generator {

    final Node node;
    final String destDir = "build/generated/sources/";
    final Map<String, TypeName> typeMap = new HashMap<>() {
        {
            put("null", null);
            put("boolean", TypeName.BOOLEAN);
            put("int", TypeName.INT);
            put("long", TypeName.LONG);
            put("float", TypeName.FLOAT);
            put("double", TypeName.DOUBLE);
            put("bytes", TypeName.BYTE);
            put("string", TypeName.get(String.class));
        }
    };

    public Generator(Node node) {
        this.node = node;
    }

    public TypeName typeName(String type) {
        if (typeMap.containsKey(type)) {
            return typeMap.get(type);
        } else {
            try {
                return TypeName.get(Class.forName(type));
            } catch (ClassNotFoundException e) {
                throw new RuntimeException("You need to define generate the type '" + type + "' first before using it", e);
            }
        }
    }

    public void generate() {
        TypeSpec.Builder builder = TypeSpec.classBuilder(node.name)
                .addModifiers(Modifier.PUBLIC);

        //create constructor
        MethodSpec defaultConstructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .build();
        builder.addMethod(defaultConstructor);

        for (Node child : node.children) {
            //add instance field
            FieldSpec fieldSpec = FieldSpec.builder(
                    typeName(child.type),
                    child.name,
                    Modifier.PROTECTED)
                    .build();
            builder.addField(fieldSpec);

            //add setter
            MethodSpec setter = MethodSpec.methodBuilder("set" + capitalize(child.name))
                    .returns(TypeName.VOID)
                    .addModifiers(Modifier.PUBLIC)
                    .addParameter(typeName(child.type), child.name)
                    .addStatement(String.format("this.%s = %s", child.name, child.name))
                    .build();
            builder.addMethod(setter);

            //add getter
            MethodSpec getter = MethodSpec.methodBuilder("set" + capitalize(child.name))
                    .addModifiers(Modifier.PUBLIC)
                    .returns(typeName(child.type))
                    .addStatement(String.format("return this.%s", child.name))
                    .build();
            builder.addMethod(getter);
        }

        //add package name
        JavaFile javaFile = JavaFile.builder(node.packageName, builder.build())
                .addFileComment("AUTO-GENERATED by JavaPoet")
                .build();

        //write to file system
        try {
            javaFile.writeTo(Paths.get(destDir));
        } catch (IOException e) {
            e.printStackTrace(System.err);
        }
    }

    public String capitalize(String input) {
        return String.format("%s%s", Character.toUpperCase(input.charAt(0)),
                input.substring(1));
    }
}
