// AUTO-GENERATED by JavaPoet
package works.hop.sample.app.model;

import java.lang.String;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public class TaskTO {
  public UUID id;

  public String name;

  public boolean completed;

  public LocalDate dateCreated;

  public List<Task> subTasks;

  public TaskTO() {
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public UUID setId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String setName() {
    return this.name;
  }

  public void setCompleted(boolean completed) {
    this.completed = completed;
  }

  public boolean setCompleted() {
    return this.completed;
  }

  public void setDateCreated(LocalDate dateCreated) {
    this.dateCreated = dateCreated;
  }

  public LocalDate setDateCreated() {
    return this.dateCreated;
  }

  public void setSubTasks(List<Task> subTasks) {
    this.subTasks = subTasks;
  }

  public List<Task> setSubTasks() {
    return this.subTasks;
  }
}
