// AUTO-GENERATED by JavaPoet
package works.hop.sample.app.model;

import java.lang.String;
import java.time.LocalDate;
import java.util.UUID;
import works.hop.javro.jdbc.annotation.Column;
import works.hop.javro.jdbc.annotation.Id;
import works.hop.javro.jdbc.annotation.Table;

@Table("tbl_task")
public class Task {
  @Id
  public UUID id;

  public String name;

  public boolean completed;

  @Column("date_created")
  public LocalDate dateCreated;

  @Column("parent_task")
  public UUID parentTask;

  public Task() {
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public UUID setId() {
    return this.id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String setName() {
    return this.name;
  }

  public void setCompleted(boolean completed) {
    this.completed = completed;
  }

  public boolean setCompleted() {
    return this.completed;
  }

  public void setDateCreated(LocalDate dateCreated) {
    this.dateCreated = dateCreated;
  }

  public LocalDate setDateCreated() {
    return this.dateCreated;
  }

  public void setParentTask(UUID parentTask) {
    this.parentTask = parentTask;
  }

  public UUID setParentTask() {
    return this.parentTask;
  }
}
