// AUTO-GENERATED by JavaPoet
package works.hop.field.jdbc.entity;

import java.lang.String;
import works.hop.field.jdbc.annotation.Column;

public class Address {
  public String city;

  @Column("state_prov")
  public String state;

  @Column("zip_code")
  public String zipCode;

  public Address() {
  }

  public void setCity(String city) {
    this.city = city;
  }

  public String setCity() {
    return this.city;
  }

  public void setState(String state) {
    this.state = state;
  }

  public String setState() {
    return this.state;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public String setZipCode() {
    return this.zipCode;
  }
}
