// AUTO-GENERATED by JavaPoet
package works.hop.javro.jdbc.entity;

import works.hop.javro.jdbc.annotation.Column;

public class Address {
    public String city;

    @Column("state_prov")
    public String state;

    @Column("zip_code")
    public String zipCode;

    public Address() {
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
}
