// AUTO-GENERATED by JavaPoet
package works.hop.javro.jdbc.entity;

import java.lang.String;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;
import works.hop.javro.jdbc.annotation.Column;
import works.hop.javro.jdbc.annotation.Id;
import works.hop.javro.jdbc.annotation.Table;

@Table("tbl_club")
public class Club {
  @Id
  public UUID id;

  @Column("date_created")
  public LocalDate dateCreated;

  @Column("last_updated")
  public LocalDateTime lastUpdated;

  public String title;

  public String activity;

  public Club() {
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public UUID setId() {
    return this.id;
  }

  public void setDateCreated(LocalDate dateCreated) {
    this.dateCreated = dateCreated;
  }

  public LocalDate setDateCreated() {
    return this.dateCreated;
  }

  public void setLastUpdated(LocalDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  public LocalDateTime setLastUpdated() {
    return this.lastUpdated;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String setTitle() {
    return this.title;
  }

  public void setActivity(String activity) {
    this.activity = activity;
  }

  public String setActivity() {
    return this.activity;
  }
}
